### ISSUE TITLE
Implement resource for managing virtual machines

### ISSUE THREAD

**Issue by dnaeon** [dnaeon/gru#23]
A good start for this would be to probably use https://github.com/apcera/libretto

**Comment by purpleidea** [comment]
Did you give up on this idea? Any background/insight into acking/nacking the use of libretto? Cheers!

**Comment by dnaeon** [comment]
Hey @purpleidea!

Libretto is nice, but it is actually solving only one part of the problem for me.

For example I'd want to be able to manage not just the Virtual Machine side of the environment, but also the compute resources, the storage, etc. for which Libretto is not well suited.

Last time I checked it there was no way to tell whether the Virtual Machine in question actually exists, which is essential for me, so that I know should I remove it or create it during Gru runs. There's no `Exists()` method in the `VirtualMachine` interface as of now in Libretto still.

Also, there's no way to reconfigure a VM, which doesn't play well with the resource properties I've introduced recently in Gru.

Ultimately importing Libretto into Gru would mean to pull lots of new dependencies and have little benefit in doing so, as it solves only one part of the problem for me.

Currently latest version of Gru ships with support for managing VMware vSphere environments - check out the [Datacenter](https://godoc.org/github.com/dnaeon/gru/resource#Datacenter), [Cluster](https://godoc.org/github.com/dnaeon/gru/resource#Cluster), [ClusterHost](https://godoc.org/github.com/dnaeon/gru/resource#ClusterHost), [Host](https://godoc.org/github.com/dnaeon/gru/resource#Host), [VirtualMachine](https://godoc.org/github.com/dnaeon/gru/resource#VirtualMachine) and [DatastoreNfs](https://godoc.org/github.com/dnaeon/gru/resource#DatastoreNfs) resources if you are intersted in it.
