### ISSUE TITLE
Implement resource triggers

### ISSUE THREAD

**Issue by dnaeon** [dnaeon/gru#33]
When a resource state changes trigger a refresh of other resources.

**Comment by kaey** [comment]
Hey.
I have 2 ideas on triggers.

1
```
svc = resource.service.new("smtpd")
svc.trigger.command["reload"] = {
    smtpd_conf:ID(),
}
svc.trigger.command["restart"] = {
    pkg:ID(),
}
```

Implementation: catalog.Run() works as it is now, except after every resource is processed, it then determines which commands need to be run (depending on whether dependency changed its state or not) and runs them. Downside is resources can't depend on services being restarted for example.


2
```
svc = resource.service.new("smtpd")
svc.trigger.state["reloaded"] = {
    smtpd_conf:ID(),
}
svc.trigger.state["restarted"] = {
    pkg:ID(),
}
```
Implementation: first graph is build, after that every resource is evaluated, then resources with triggered states are added in a graph and it's gets rebuilt. This is harder to do, because graph implementation will need to be changed.


Thoughts?

**Comment by dnaeon** [comment]
Thanks for your input on this one!

I'm currently on my mobile, and will get back on this one tomorrow when I'm in front of the computer.

Thanks again and chat later!

**Comment by dnaeon** [comment]
Hey @kaey 

Here are my thoughts about the resource triggers.

What you have described is I think a way to have a resource *subscribe* to changes to other resources.

I was thinking about this more in the following way.

The `resource.Resource` interface will have an addition method - `Refresh()` for instance, which will be responsible for handling notifications/triggers from other resources. For `Service` resource this could be a restart or reload of the service for example. The `resource.Base` type will be implementing `Refresh()` by simply returning a `ErrNotImplemented`, so that applicable resources that can be refreshed should provide their proper implementation of a *refresh*.

If we have a resource which notifies/triggers other resources - then this should automatically create an edge between these two resources in the dependency graph. For instance if resource `A` notifies/triggers resource `B`, then this should create an edge `B -> A` in the dependency graph, so that `A` always gets evaluated and processed before `B`. This would not require any changes to the existing graph implementation and would make it possible to use the existing graph in the catalog.

The conditions that need to be met for a resource to be able to notify/trigger/refresh other resources in `Catalog.Run` should be.

* The resource evaluates and processes fine with no errors
* The state of the resource has changed - meaning that it called `Create()`, `Delete()` or `Update()` methods
* The `resource` package should include an error `UpToDate` indicating that resources are up-to-date and did not change during catalog run

Once a resource successfully evaluates and processes fine it should add all resources it notifies to some registry.

Something else that we should consider is unscheduling refreshes/triggers - for example a service cannot be refreshed/reloaded if the service is not running. That should be simple to do - if the resource goes through `Create`, `Delete` or `Update` and it has it's refresh/notify flag set on, then we simply reset it back to off. In other words I think that a resource should be refreshed only when it is in the desired state and got an event from other resources.

What do you think about it?

**Comment by kaey** [comment]
>What you have described is I think a way to have a resource subscribe to changes to other resources.

Yes. Since you already specify dependencies, subscribing to changes of those deps in the same place feels natural.

>The resource.Base type will be implementing Refresh() by simply returning a ErrNotImplemented

This is not possible since you can't override methods. Either you force all resources to implement Refresh() or use interface assertion in catalog.Run() to see whether resource has Refresh().

>If we have a resource which notifies/triggers other resources - then this should automatically create an edge between these two resources in the dependency graph.
SGTM. I have over-complicated my second idea.

Three things:
1. What config should look like to the end user?
2. You didn't mention how to trigger different actions - for example I want to restart process if its binary updated and reload it if only config changed.
3. I would prefer, like you said, resources subscribing to changes of others, though such notifications can be implemented to work both ways.

**Comment by dnaeon** [comment]
> This is not possible since you can't override methods. Either you force all resources to implement Refresh() or use interface assertion in catalog.Run() to see whether resource has Refresh().

Actually you can :)

Here's an example of what I mean.

* https://play.golang.org/p/MylDO2KHiI

The idea is that only applicable resources for a refresh would implement the actual `Refresh()` method, while the rest will simply return what `Base.Refresh()` returns.

> What config should look like to the end user?

It could be something along the following.

```lua
-- Manage the SNMP daemon service                                                                                                                 
svc = resource.service.new("snmpd")                                                                                                               
svc.state = "running"                                                                                                                             
svc.enable = true                                                                                                                                 
                                                                                                                                                  
-- Manage the config file for SNMP daemon                                                                                                         
config = resource.file.new("/path/to/snmpd.conf")                                                                                                 
config.state = "present"                                                                                                                          
config.source = "/path/to/source/file/to/use"                                                                                                     
config.refresh = { svc:ID() } --> automatically creates an edge svc -> config                                                                     
```

This code would call the `Service.Refresh()` method whenever  the `File` resource changes, but is limited to what the `Service.Refresh()` implementation actually is - either a restart or reload, but not much else.

> You didn't mention how to trigger different actions - for example I want to restart process if its binary updated and reload it if only config changed.

Good point!

This sounds like having custom handlers/triggers per resource, and I like that! For example a resource can register custom handlers/triggers, which other resources can call if their state changes.

Here's an example code using the notify/trigger pattern.

```lua
--
-- Notify/trigger pattern example code
--

-- Manage the SNMP daemon service
svc = resource.service.new("snmpd")
svc.state = "running"
svc.enable = true

--
-- Register a "restart" handler for the service
--
-- handler.service.restart is a builtin Go function registered in Lua
--
svc.handlers["restart"] = handler.service.restart("snmpd")

-- .. or a regular Lua function instead
svc.handlers["restart"] = function()
   print("The service will be restarted")
end

-- Register a reload handler as well
svc.handlers["reload"] = handler.service.reload("snmpd")

-- Manage the config file for SNMP daemon
config = resource.file.new("/path/to/snmpd.conf")
config.state = "present"
config.source = "/path/to/source/file/to/use"
config.trigger = { svc.handlers["reload"] } --> reload service on config change

-- Manage the SNMP daemon package
pkg = resource.package.new("snmpd")
pkg.state = "present"
pkg.trigger = { svc.handlers["restart"] } --> restart service on package change
```

Same thing, but using a subscribe pattern as you suggested.

```lua
--
-- Subscribe pattern example
--

-- Manage the SNMP daemon package
pkg = resource.package.new("snmpd")
pkg.state = "present"

-- Manage the config file for SNMP daemon
config = resource.file.new("/path/to/snmpd.conf")
config.state = "present"
config.source = "/path/to/source/file/to/use"
config.require = { pkg:ID() }

-- Manage the SNMP daemon service and register handlers
svc = resource.service.new("snmpd")
svc.state = "running"
svc.enable = true

svc.handlers["restart"] = handler.service.restart("snmpd")

-- .. or a regular Lua function instead
svc.handlers["restart"] = function()
   print("The service will be restarted")
end

-- Register a reload handler as well
svc.handlers["reload"] = handler.service.reload("snmpd")

-- Subscribe to changes in the config file resource and reload service
svc.subscribe[config:ID()] = svc.handlers["reload"]

-- Subscribe to changes in the package resource and restart service
svc.subscribe[pkg:ID()] = svc.handlers["restart"]
```

> I would prefer, like you said, resources subscribing to changes of others, though such notifications can be implemented to work both ways.

Completely agree, subscribing seems more natural to me as well, but we can easily have both ways implemented.

What do you think?

**Comment by kaey** [comment]
>Actually you can :)

Looks like I've confused it with something else.

So you want users to define handlers in lua, do you think it's needed or do you want to extend current capabilities of lua (for example allow writing resources in it)?

I was thinking about defining handlers like this (naming doesn't matter):
```
func (s *Service) Command(cmd string) error {
        switch cmd {
        case "reload":
                return exec.Command("service", s.Name, "onereload").Run()
        case "restart":
                return exec.Command("service", s.Name, "onerestart").Run()
        }

        return fmt.Errorf("unsupported command %q", cmd)
}
```

And lastly I think some services might want to depend on others being restarted or reloaded or something, though I can't think of concrete examples. How would you implement it with your proposal?

**Comment by dnaeon** [comment]
> So you want users to define handlers in lua, do you think it's needed or do you want to extend current capabilities of lua (for example allow writing resources in it)?

Being able to write the triggers/handlers in Lua I think would be more flexible in the long term. Of course we can still write handlers/triggers in Go, we just need to make sure to register them in Lua as a valid function and then simply use it.

Being able to write resources in Lua (besides the Go builtin ones) is something I've considered as well, but that is probably something as a future work. If you'd like to pick this one that would be great!

What you've described in the code sample is limited to only specific commands that the resource can understand and process. Adding a new command to it would mean to recompile Gru.

I've just committed and pushed my idea of triggers/handlers in the `triggers` branch. Please check it and let me know how it looks.

Here's a working example of using triggers from the `triggers` branch of the project.

```lua
-- Manage the SNMP daemon package
pkg = resource.package.new("snmpd")
pkg.state = "present"

-- Manage the config file for SNMP daemon
config = resource.file.new("/path/to/snmpd.conf")
config.state = "present"
config.source = "/path/to/source/file/to/use"
config.require = { pkg:ID() }

-- Manage the SNMP daemon service
svc = resource.service.new("snmpd")
svc.state = "running"
svc.enable = true

-- Subscribe to changes in the config file resource
svc.subscribe[config:ID()] = function()
   log("service will be reloaded")
end

-- Subscribe to changes in the package resource
svc.subscribe[pkg:ID()] = function()
   log("service will be restarted")
end

-- Add resources to the catalog
catalog:add(pkg, config, svc)
```

Let me know what do you think about it.

Thanks!

**Comment by dnaeon** [comment]
I've just merged the `triggers` branch to `master`.

Feel free to submit another issue or PR if you see a need to improve the current triggers implementation.

Thanks!
